//! Writes `src/Tables.mw` and `src/Cases.mw` for lexopt.
//!
//! ```text
//! cargo run --release -- <package root>
//! ```
//!
//! The tables are the characters Rust's `{:?}` writes as `\u{…}`, which the
//! crate's error messages use; they come from the Rust that builds this. The
//! cases are random command lines, each read by a random sequence of calls,
//! with what the crate answers to each. The library is ported by hand into
//! `src/`, and the crate's source is fingerprinted.

use lexopt::{Arg, Parser, ValueExt};
use std::ffi::OsString;
use std::fmt::Write as _;
use std::path::PathBuf;

/// The crate version pinned in `Cargo.toml`.
const UPSTREAM_VERSION: &str = "0.3.2";

/// The fingerprint of the crate's source, which `src/` ports.
const SOURCES: u64 = 0x8f7b_c6b8_fd67_69e4;

fn main() {
    let root = PathBuf::from(std::env::args().nth(1).unwrap_or_else(|| "../..".into()));

    let print = fingerprint(include_str!(concat!(env!("OUT_DIR"), "/sources.rs.txt")));
    if print != SOURCES {
        eprintln!(
            "error: lexopt is not the version src/ ports.\n\
             Compare its source in {} with the previous version, carry any change\n\
             into src/, then set SOURCES in scripts/generate/src/main.rs to\n\
             {print:#x}",
            env!("UPSTREAM_DIR")
        );
        std::process::exit(1);
    }

    for (name, text) in [("Tables", tables()), ("Cases", cases())] {
        let path = root.join(format!("src/{name}.mw"));
        std::fs::write(&path, &text).unwrap();
        eprintln!("wrote {} ({} bytes)", path.display(), text.len());
    }
}

/// FNV-1a: stable across builds, which `DefaultHasher` does not promise.
fn fingerprint(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in text.bytes() {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

// --- encoding -----------------------------------------------------------------------

/// A number as `digits` base-64 digits, most significant first, each digit the
/// character `'0' + d`: `'0'` to `'o'`, one contiguous run of ASCII.
fn digits(out: &mut String, value: u64, digits: u32) {
    assert!(
        value < 1 << (6 * digits),
        "{value} does not fit in {digits} digits"
    );
    for k in (0..digits).rev() {
        out.push(char::from(b'0' + ((value >> (6 * k)) & 63) as u8));
    }
}

/// A string, as its length in bytes (3 digits) and then its bytes.
fn text(out: &mut String, s: &str) {
    digits(out, s.len() as u64, 3);
    out.push_str(s);
}

/// `text` as one Meadow string literal, broken with `\`-newline every `width`
/// characters. Only printable ASCII is written raw; a space that would start a
/// line is `\x20`, since a continuation drops leading whitespace.
fn long_literal(text: &str, width: usize) -> String {
    let mut out = String::with_capacity(text.len() + text.len() / width * 4 + 2);
    out.push('"');
    for (i, c) in text.chars().enumerate() {
        let line_start = i > 0 && i % width == 0;
        if line_start {
            out.push_str("\\\n    ");
        }
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            ' ' if line_start => out.push_str("\\x20"),
            ' '..='~' => out.push(c),
            _ => {
                let _ = write!(out, "\\u{{{:X}}}", u32::from(c));
            }
        }
    }
    out.push('"');
    out
}

// --- tables -------------------------------------------------------------------------

/// Whether `{:?}` writes `c` as `\u{…}`.
fn escaped_as_unicode(c: char) -> bool {
    let quoted = format!("{:?}", c.to_string());
    quoted.starts_with("\"\\u{")
}

fn tables() -> String {
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    for cp in 0..=0x10_FFFFu32 {
        let Some(c) = char::from_u32(cp) else {
            continue;
        };
        if !escaped_as_unicode(c) {
            continue;
        }
        match ranges.last_mut() {
            // Surrogates are not characters; a run may span them.
            Some((_, end)) if *end + 1 == cp || (*end == 0xD7FF && cp == 0xE000) => *end = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    let mut body = String::new();
    for (lo, hi) in &ranges {
        digits(&mut body, u64::from(*lo), 4);
        digits(&mut body, u64::from(*hi), 4);
    }
    let (major, minor, update) = char::UNICODE_VERSION;
    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from the Rust standard library, Unicode
-- {major}.{minor}.{update}.
-- Do not edit: run the script again instead.
--
-- The {} runs of characters Rust's `{{:?}}` writes as `\\u{{…}}`: those that are
-- not printable, and grapheme extenders. Each run is its first and last code
-- point, 4 base-64 digits each (`'0' + d`, most significant first).
--
-- Copyright the Rust project contributors, and the Meadow port's authors.
-- Licensed under MIT: see COPYRIGHT.

@pub(pkg) def escapedRanges =
  {}",
        ranges.len(),
        long_literal(&body, 96)
    );
    out
}

// --- cases --------------------------------------------------------------------------

/// A small deterministic generator, so that the cases are the same on every run.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }

    fn chance(&mut self, percent: u64) -> bool {
        self.below(100) < percent
    }

    fn pick<T: Copy>(&mut self, xs: &[T]) -> T {
        xs[self.below(xs.len() as u64) as usize]
    }
}

const PIECES: &[&str] = &[
    "-a",
    "-b",
    "-abc",
    "-o",
    "-ovalue",
    "-o=value",
    "-o=",
    "-=",
    "-=x",
    "-a=b",
    "-ab=c",
    "-é",
    "-éü=ß",
    "-\u{301}",
    "-\u{1f600}x",
    "--",
    "-",
    "---",
    "--long",
    "--long=value",
    "--long=",
    "--=",
    "--=x",
    "--é=ü",
    "--x=y=z",
    "value",
    "42",
    "-42",
    "",
    " ",
    "a b",
    "tab\there",
    "new\nline",
    "quote\"s",
    "back\\slash",
    "it's",
    "\u{0}",
    "\u{7f}",
    "\u{85}",
    "\u{ad}",
    "\u{200b}",
    "\u{301}x",
    "\u{fe0f}",
    "\u{e000}",
    "\u{10ffff}",
    "日本",
    "\u{1f468}\u{200d}\u{1f469}",
    "=",
    "-v",
    "--verbose",
];

fn arg_text(arg: &Arg<'_>) -> String {
    match arg {
        Arg::Short(c) => format!("short {c}"),
        Arg::Long(name) => format!("long {name}"),
        Arg::Value(v) => format!("value {}", v.to_string_lossy()),
    }
}

fn list(values: &[OsString]) -> String {
    let parts: Vec<String> = values
        .iter()
        .map(|v| v.to_string_lossy().into_owned())
        .collect();
    format!("[{}]", parts.join("|"))
}

fn maybe(v: Option<&str>) -> String {
    match v {
        Some(s) => format!("some {s}"),
        None => "none".to_string(),
    }
}

/// Runs call `op` on the parser, writing what `Tests.mw` needs to repeat it
/// and returning what the crate answered.
fn run(op: u64, parser: &mut Parser, rng: &mut Rng, out: &mut String) -> String {
    match op {
        0 => match parser.next() {
            Ok(Some(arg)) => {
                let shown = arg_text(&arg);
                format!("{shown} / {}", arg.unexpected())
            }
            Ok(None) => "none".to_string(),
            Err(e) => format!("error {e}"),
        },
        1 => match parser.value() {
            Ok(v) => format!("ok {}", v.to_string_lossy()),
            Err(e) => format!("error {e}"),
        },
        2 => match parser.values() {
            Ok(vs) => list(&vs.collect::<Vec<_>>()),
            Err(e) => format!("error {e}"),
        },
        3 => maybe(parser.optional_value().as_ref().and_then(|v| v.to_str())),
        4 => match parser.raw_args() {
            Ok(raw) => list(&raw.collect::<Vec<_>>()),
            Err(e) => format!("error {e}"),
        },
        5 => match parser.raw_args() {
            Ok(raw) => maybe(raw.peek().and_then(|v| v.to_str())),
            Err(e) => format!("error {e}"),
        },
        6 => {
            let prefix = rng.pick(&["-", "v", "", "x"]);
            text(out, prefix);
            match parser.raw_args() {
                Ok(mut raw) => {
                    let taken = raw.next_if(|a| a.to_string_lossy().starts_with(prefix));
                    maybe(taken.as_ref().and_then(|v| v.to_str()))
                }
                Err(e) => format!("error {e}"),
            }
        }
        7 => match parser.try_raw_args() {
            Some(raw) => format!("some {}", list(&raw.collect::<Vec<_>>())),
            None => "none".to_string(),
        },
        8 => {
            let on = rng.chance(50);
            digits(out, u64::from(on), 1);
            parser.set_short_equals(on);
            String::new()
        }
        9 => maybe(parser.bin_name()),
        _ => match parser.value() {
            Ok(v) => match v.parse_with(|s| {
                if !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit()) {
                    Ok(s.len())
                } else {
                    Err("not a number")
                }
            }) {
                Ok(n) => format!("parsed {n}"),
                Err(e) => format!("error {e}"),
            },
            Err(e) => format!("error {e}"),
        },
    }
}

fn cases() -> String {
    let mut rng = Rng(0x1e70_b7c0_c0ff_ee42);
    let mut body = String::new();
    let count = 4000;
    for _ in 0..count {
        let n = rng.below(8);
        let args: Vec<String> = (0..n).map(|_| rng.pick(PIECES).to_string()).collect();
        let with_name = rng.chance(30);
        digits(&mut body, u64::from(with_name), 1);
        digits(&mut body, args.len() as u64, 1);
        for a in &args {
            text(&mut body, a);
        }
        let mut parser = if with_name {
            Parser::from_iter(args)
        } else {
            Parser::from_args(args)
        };
        let ops = rng.below(12) + 1;
        digits(&mut body, ops, 1);
        for _ in 0..ops {
            // `next` most of the time, as a real program calls it.
            let op = if rng.chance(45) { 0 } else { rng.below(11) };
            digits(&mut body, op, 1);
            let answer = run(op, &mut parser, &mut rng, &mut body);
            text(&mut body, &answer);
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from lexopt {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
-- Inputs, with what the crate makes of them, for `Tests.mw`: {count} command
-- lines, each read by a random sequence of calls.
--
-- Copyright Jan Verbeek and the lexopt contributors, and the Meadow port's
-- authors. Licensed under MIT: see LICENSE and COPYRIGHT.

-- Each case is whether the first argument is the program's name, the
-- arguments, and the calls. A call is its number, anything it takes, and what
-- the crate answered. A number is base-64 digits; a string is its length in
-- bytes (3 digits) and then its bytes.
@cfg(test)
@pub(pkg) def cases =
  {}",
        long_literal(&body, 96)
    );
    out
}
